apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Software\Minikube\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8080
  selector:
    io.kompose.service: adminer
status:
  loadBalancer: {}
