apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Software\Minikube\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: adonis-app
  name: adonis_app
spec:
  ports:
    - name: "3333"
      port: 3333
      targetPort: 3333
    - name: "9229"
      port: 9229
      targetPort: 9229
  selector:
    io.kompose.service: adonis-app
status:
  loadBalancer: {}
