apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Software\Minikube\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: kafdrop
  name: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafdrop
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Software\Minikube\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: kafdrop
    spec:
      containers:
        - env:
            - name: KAFKA_BROKERCONNECT
              value: kafka:9093
          image: obsidiandynamics/kafdrop
          name: kafdrop
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
