apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Software\Minikube\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: kafdrop
  name: kafdrop
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: kafdrop
status:
  loadBalancer: {}
